deploy-local:
	forge script script/ModularResolverV1Script.s.sol --rpc-url http://localhost:8545 --broadcast --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

deploy-goerli:
	forge script script/CCIPResolverScript.sol --broadcast --rpc-url https://rpc.ankr.com/eth_goerli

deploy-world-polygon:
	forge script script/WorldNameResolverScript.sol --broadcast --rpc-url https://rpc.ankr.com/polygon
